ARG PGVERSION=9.6

#
# We use the Docker image for postgres so as to benefit from entry point
# scripts with some level of tweakability. We could use a bare debian image
# instead, but we would have to provide and maintain those scripts.
#
FROM postgres:${PGVERSION}

ARG PGVERSION

COPY allow-logical-rep.sh /docker-entrypoint-initdb.d
