ARG PGVERSION=16
ARG PGCOPYDB_IMAGE=pgcopydb:latest

# Create a named stage from the pgcopydb image for COPY --from
FROM $PGCOPYDB_IMAGE as pgcopydb_source

FROM debian:bookworm-slim

ARG PGVERSION

RUN echo 'Acquire::Retries "3";' > /etc/apt/apt.conf.d/80-retries

RUN apt-get update \
  && apt-get install -y --no-install-recommends \
    ca-certificates \
    curl \
    gdb \
    git \
    gnupg \
    htop \
    jq \
    libgc1 \
    libpq5 \
    lsof \
    make \
    openssl \
    postgresql-client-common \
    psmisc \
    strace \
    sudo \
    tmux \
    watch \
  && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc \
  | gpg --dearmor -o /usr/share/keyrings/pgdg.gpg
RUN echo "deb [signed-by=/usr/share/keyrings/pgdg.gpg] http://apt.postgresql.org/pub/repos/apt bookworm-pgdg main ${PGVERSION}" > /etc/apt/sources.list.d/pgdg.list

# bypass initdb of a "main" cluster
RUN echo 'create_main_cluster = false' | sudo tee -a /etc/postgresql-common/createcluster.conf
RUN apt-get update \
  && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    postgresql-${PGVERSION} \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/
RUN git clone --depth 1 https://github.com/devrimgunduz/pagila.git

#RUN adduser --disabled-password --gecos '' --home /var/lib/postgres docker
#RUN adduser docker sudo
RUN useradd -rm -d /var/lib/postgres -s /bin/bash -g postgres -G sudo docker
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

COPY --from=pgcopydb_source /usr/local/bin/sqlite3 /usr/local/bin
COPY --from=pgcopydb_source /usr/local/bin/pgcopydb /usr/local/bin

COPY .psqlrc /var/lib/postgres
COPY .sqliterc /var/lib/postgres
COPY cleanup.mk /var/lib/postgres
