\ir 1-exclusion-constraints.sql
\ir 2-inherit.sql
\ir 3-collations.sql
\ir 4-list-table-split.sql
\ir 5-long-index-def.sql
\ir 6-multiline-table-name.sql
\ir 7-identity.sql
\ir 8-string-escape.sql
\ir 9-table-with-zero-cols.sql
\ir 10-search-path-index-enum.sql
\ir 11-check-constraint.sql
