FROM pgcopydb

USER root

RUN apt-get update \
    && apt-get install -y --no-install-recommends jq \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/pgcopydb
COPY ./inject.sh inject.sh
COPY ./dml.sql dml.sql

USER docker
CMD ["/usr/src/pgcopydb/inject.sh"]
