ARG PGVERSION=16
FROM postgres:${PGVERSION}

ARG PGVERSION=16
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
      postgresql-${PGVERSION}-wal2json \
      postgresql-13-partman \
      postgresql-13-postgis-3 \
      postgis \
    && rm -rf /var/lib/apt/lists/*
