# Copyright (c) 2021 The PostgreSQL Global Development Group.
# Licensed under the PostgreSQL License.

test: build up ;

up:
	docker-compose up

down:
	docker-compose down

build:
	docker-compose build

.PHONY: up down build test
